name: Test all labs on Java 17
on:
  push:
    branches: [master]

jobs:
  test-labs-java-17:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Build and test with Maven
      run: |
        cd lab
        ./mvnw clean package
    - name: Build and test with Gradle
      run: |
        cd lab
        ./gradlew clean build
